-- ============================================================
-- SINONIMOS PUBLICOS - EventosBibliotecasDB (v4)
-- Executar como SYSDBA
-- ============================================================

-- Tabelas
CREATE PUBLIC SYNONYM BIBLIOTECA
    FOR usr_eventosdb.BIBLIOTECA;
CREATE PUBLIC SYNONYM HORARIO_BIBLIOTECA
    FOR usr_eventosdb.HORARIO_BIBLIOTECA;
CREATE PUBLIC SYNONYM BIBLIOTECA_RESPONSAVEL
    FOR usr_eventosdb.BIBLIOTECA_RESPONSAVEL;
CREATE PUBLIC SYNONYM EVENTO
    FOR usr_eventosdb.EVENTO;
CREATE PUBLIC SYNONYM HORARIO_EVENTO
    FOR usr_eventosdb.HORARIO_EVENTO;
CREATE PUBLIC SYNONYM PARTICIPACAO_EVENTO
    FOR usr_eventosdb.PARTICIPACAO_EVENTO;
CREATE PUBLIC SYNONYM AVALIACAO_EVENTO
    FOR usr_eventosdb.AVALIACAO_EVENTO;
CREATE PUBLIC SYNONYM EVENTO_RECURSO
    FOR usr_eventosdb.EVENTO_RECURSO;
CREATE PUBLIC SYNONYM AUDITORIA_EVENTOS
    FOR usr_eventosdb.AUDITORIA_EVENTOS;

-- Vistas de servico
CREATE PUBLIC SYNONYM V_PROGRAMACAO_EVENTOS
    FOR usr_eventosdb.V_PROGRAMACAO_EVENTOS;
CREATE PUBLIC SYNONYM V_HORARIOS_BIBLIOTECAS
    FOR usr_eventosdb.V_HORARIOS_BIBLIOTECAS;
CREATE PUBLIC SYNONYM V_BIBLIOTECAS_ACTIVAS
    FOR usr_eventosdb.V_BIBLIOTECAS_ACTIVAS;
CREATE PUBLIC SYNONYM V_EVENTO_GLOBAL
    FOR usr_eventosdb.V_EVENTO_GLOBAL;

-- Vistas de fragmento originais
CREATE PUBLIC SYNONYM FRAG_EVENTO_SUL
    FOR usr_eventosdb.FRAG_EVENTO_SUL;
CREATE PUBLIC SYNONYM FRAG_EVENTO_CENTRO
    FOR usr_eventosdb.FRAG_EVENTO_CENTRO;
CREATE PUBLIC SYNONYM FRAG_EVENTO_NORTE
    FOR usr_eventosdb.FRAG_EVENTO_NORTE;

-- Vistas de fragmentacao horizontal (Tarefa A1)
CREATE PUBLIC SYNONYM VW_FRAG_EVENTO_FUTURO
    FOR usr_eventosdb.VW_FRAG_EVENTO_FUTURO;
CREATE PUBLIC SYNONYM VW_FRAG_EVENTO_PASSADO
    FOR usr_eventosdb.VW_FRAG_EVENTO_PASSADO;

-- Vistas de fragmentacao derivada (Tarefa A2)
CREATE PUBLIC SYNONYM VW_FRAG_PARTICIPACAO_FUTURO
    FOR usr_eventosdb.VW_FRAG_PARTICIPACAO_FUTURO;
CREATE PUBLIC SYNONYM VW_FRAG_PARTICIPACAO_PASSADO
    FOR usr_eventosdb.VW_FRAG_PARTICIPACAO_PASSADO;

-- Verificar
SELECT SYNONYM_NAME, TABLE_OWNER, TABLE_NAME
FROM ALL_SYNONYMS
WHERE TABLE_OWNER = 'USR_EVENTOSDB'
ORDER BY SYNONYM_NAME;