-- ============================================================
-- SINONIMOS PUBLICOS - EventosBibliotecasDB (v4)
-- Executar como SYSDBA
-- ============================================================

-- Tabelas
CREATE OR REPLACE PUBLIC SYNONYM BIBLIOTECA
    FOR usr_eventosdb.BIBLIOTECA;
CREATE OR REPLACE PUBLIC SYNONYM HORARIO_BIBLIOTECA
    FOR usr_eventosdb.HORARIO_BIBLIOTECA;
CREATE OR REPLACE PUBLIC SYNONYM BIBLIOTECA_RESPONSAVEL
    FOR usr_eventosdb.BIBLIOTECA_RESPONSAVEL;
CREATE OR REPLACE PUBLIC SYNONYM EVENTO
    FOR usr_eventosdb.EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM HORARIO_EVENTO
    FOR usr_eventosdb.HORARIO_EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM PARTICIPACAO_EVENTO
    FOR usr_eventosdb.PARTICIPACAO_EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM AVALIACAO_EVENTO
    FOR usr_eventosdb.AVALIACAO_EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM EVENTO_RECURSO
    FOR usr_eventosdb.EVENTO_RECURSO;
CREATE OR REPLACE PUBLIC SYNONYM AUDITORIA_EVENTOS
    FOR usr_eventosdb.AUDITORIA_EVENTOS;

-- Vistas de servico
CREATE OR REPLACE PUBLIC SYNONYM V_PROGRAMACAO_EVENTOS
    FOR usr_eventosdb.V_PROGRAMACAO_EVENTOS;
CREATE OR REPLACE PUBLIC SYNONYM V_HORARIOS_BIBLIOTECAS
    FOR usr_eventosdb.V_HORARIOS_BIBLIOTECAS;
CREATE OR REPLACE PUBLIC SYNONYM V_BIBLIOTECAS_ACTIVAS
    FOR usr_eventosdb.V_BIBLIOTECAS_ACTIVAS;
CREATE OR REPLACE PUBLIC SYNONYM V_EVENTO_GLOBAL
    FOR usr_eventosdb.V_EVENTO_GLOBAL;

-- Vistas de fragmento originais
CREATE OR REPLACE PUBLIC SYNONYM FRAG_EVENTO_SUL
    FOR usr_eventosdb.FRAG_EVENTO_SUL;
CREATE OR REPLACE PUBLIC SYNONYM FRAG_EVENTO_CENTRO
    FOR usr_eventosdb.FRAG_EVENTO_CENTRO;
CREATE OR REPLACE PUBLIC SYNONYM FRAG_EVENTO_NORTE
    FOR usr_eventosdb.FRAG_EVENTO_NORTE;

-- Vistas de fragmentacao horizontal (Tarefa A1)
CREATE OR REPLACE PUBLIC SYNONYM VW_FRAG_EVENTO_FUTURO
    FOR usr_eventosdb.VW_FRAG_EVENTO_FUTURO;
CREATE OR REPLACE PUBLIC SYNONYM VW_FRAG_EVENTO_PASSADO
    FOR usr_eventosdb.VW_FRAG_EVENTO_PASSADO;

-- Vistas de fragmentacao derivada (Tarefa A2)
CREATE OR REPLACE PUBLIC SYNONYM VW_FRAG_PARTICIPACAO_FUTURO
    FOR usr_eventosdb.VW_FRAG_PARTICIPACAO_FUTURO;
CREATE OR REPLACE PUBLIC SYNONYM VW_FRAG_PARTICIPACAO_PASSADO
    FOR usr_eventosdb.VW_FRAG_PARTICIPACAO_PASSADO;

-- Vistas acedidas via dblink pelo NacionalDB (dashboard, bibliotecas, eventos)
CREATE OR REPLACE PUBLIC SYNONYM VW_EVENTOS_PROXIMOS          FOR usr_eventosdb.VW_EVENTOS_PROXIMOS;
CREATE OR REPLACE PUBLIC SYNONYM VW_EVENTOS_COMPLETOS         FOR usr_eventosdb.VW_EVENTOS_COMPLETOS;
CREATE OR REPLACE PUBLIC SYNONYM VW_BIBLIOTECAS_OPERACIONAIS  FOR usr_eventosdb.VW_BIBLIOTECAS_OPERACIONAIS;
CREATE OR REPLACE PUBLIC SYNONYM VW_HORARIOS_BIBLIOTECA_SEMANA FOR usr_eventosdb.VW_HORARIOS_BIBLIOTECA_SEMANA;
CREATE OR REPLACE PUBLIC SYNONYM VW_PARTICIPACOES_EVENTOS     FOR usr_eventosdb.VW_PARTICIPACOES_EVENTOS;
CREATE OR REPLACE PUBLIC SYNONYM INSERE_PARTICIPACAO_EVENTO   FOR usr_eventosdb.INSERE_PARTICIPACAO_EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_EVENTO                   FOR usr_eventosdb.SEQ_EVENTO;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_AVALIACAO                FOR usr_eventosdb.SEQ_AVALIACAO;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_HORARIO_EVENTO           FOR usr_eventosdb.SEQ_HORARIO_EVENTO;

-- Autenticacao usa snapshots locais — funciona mesmo com NacionalDB offline
CREATE OR REPLACE PUBLIC SYNONYM FUNCIONARIO
    FOR usr_eventosdb.repl_funcionarios;
CREATE OR REPLACE PUBLIC SYNONYM FUNCAO_FUNCIONARIO
    FOR usr_eventosdb.repl_funcao_funcionario;

-- Snapshots locais (acesso directo pelo app_eventosdb sem prefixo de schema)
CREATE OR REPLACE PUBLIC SYNONYM snap_leitor             FOR usr_eventosdb.snap_leitor;
CREATE OR REPLACE PUBLIC SYNONYM repl_funcionarios       FOR usr_eventosdb.repl_funcionarios;
CREATE OR REPLACE PUBLIC SYNONYM repl_funcao_funcionario FOR usr_eventosdb.repl_funcao_funcionario;
