-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-01 13:32:58 CAT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



DROP TABLE ADULTO CASCADE CONSTRAINTS
;

DROP TABLE BIBLIOTECA CASCADE CONSTRAINTS
;

DROP TABLE CATEGORIA CASCADE CONSTRAINTS
;

DROP TABLE CERTIFICADO_DOACAO CASCADE CONSTRAINTS
;

DROP TABLE CRIANCA CASCADE CONSTRAINTS
;

DROP TABLE DOACAO CASCADE CONSTRAINTS
;

DROP TABLE DOADOR CASCADE CONSTRAINTS
;

DROP TABLE EBOOK CASCADE CONSTRAINTS
;

DROP TABLE EMPRESTIMO CASCADE CONSTRAINTS
;

DROP TABLE EVENTO CASCADE CONSTRAINTS
;

DROP TABLE EVENTO_RECURSO CASCADE CONSTRAINTS
;

DROP TABLE FUNCAO_FUNCIONARIO CASCADE CONSTRAINTS
;

DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS
;

DROP TABLE HORARIO_EV_BIB CASCADE CONSTRAINTS
;

DROP TABLE ITEM_DOACAO CASCADE CONSTRAINTS
;

DROP TABLE LEITOR CASCADE CONSTRAINTS
;

DROP TABLE LIVRO_FISICO CASCADE CONSTRAINTS
;

DROP TABLE MATERIAL_BIBLIOGRAFICO CASCADE CONSTRAINTS
;

DROP TABLE PARTICIPACAO_EVENTO CASCADE CONSTRAINTS
;

DROP TABLE PERIODICO CASCADE CONSTRAINTS
;

DROP TABLE PROFESSOR CASCADE CONSTRAINTS
;

DROP TABLE TRANSFERENCIA CASCADE CONSTRAINTS
;

CREATE TABLE ADULTO
    (
     num_cartao VARCHAR2 (12 BYTE)  NOT NULL ,
     profissao  VARCHAR2 (50 BYTE)
    )
;
ALTER TABLE ADULTO
    ADD CONSTRAINT ADULTO_PK PRIMARY KEY ( num_cartao ) ;

CREATE TABLE BIBLIOTECA
    (
     id_biblioteca       NUMBER  NOT NULL ,
     nome_biblioteca     VARCHAR2 (100 BYTE)  NOT NULL ,
     localizacao         VARCHAR2 (200 BYTE)  NOT NULL ,
     contacto_biblioteca VARCHAR2 (50 BYTE)  NOT NULL ,
     id_responsavel      NUMBER
    )
;
ALTER TABLE BIBLIOTECA
    ADD CONSTRAINT BIBLIOTECA_PK PRIMARY KEY ( id_biblioteca ) ;

ALTER TABLE BIBLIOTECA
    ADD CONSTRAINT BIBLIOTECA__UN UNIQUE ( nome_biblioteca ) ;

CREATE TABLE CATEGORIA
    (
     id_categoria  NUMBER  NOT NULL ,
     area_tematica VARCHAR2 (50 BYTE)  NOT NULL ,
     faixa_etaria  VARCHAR2 (17 BYTE)  NOT NULL ,
     nivel_leitura VARCHAR2 (12 BYTE)  NOT NULL
    )
;

ALTER TABLE CATEGORIA
    ADD
    CHECK (faixa_etaria IN ('Infantil','Juvenil','Adulto','Todas as Idades'))
;

ALTER TABLE CATEGORIA
    ADD
    CHECK (nivel_leitura IN ('Basico','Intermedio','Avancado'))
;
ALTER TABLE CATEGORIA
    ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( id_categoria ) ;

CREATE TABLE CERTIFICADO_DOACAO
    (
     id_certificado     NUMBER  NOT NULL ,
     num_certificado VARCHAR2 (20 BYTE)  NOT NULL ,
     original_numero    VARCHAR2(30),
     data_emissao       DATE  NOT NULL ,
     tipo_certificado   VARCHAR2 (20 BYTE)  NOT NULL ,
     observacoes        VARCHAR2 (300 BYTE) ,
     id_doacao          NUMBER  NOT NULL
    )
;

ALTER TABLE CERTIFICADO_DOACAO
    ADD
    CHECK (tipo_certificado IN ('Original','Reemissao'))
;
ALTER TABLE CERTIFICADO_DOACAO
    ADD CONSTRAINT CERTIFICADO_DOACAO_PK PRIMARY KEY ( id_certificado ) ;

ALTER TABLE CERTIFICADO_DOACAO
    ADD CONSTRAINT CERTIFICADO_DOACAO__UN UNIQUE ( num_certificado ) ;

CREATE TABLE CRIANCA
    (
     num_cartao           VARCHAR2 (12 BYTE)  NOT NULL ,
     nome_responsavel     VARCHAR2 (100 BYTE)  NOT NULL ,
     telefone_responsavel VARCHAR2 (50 BYTE)  NOT NULL ,
     escola_frequenta     VARCHAR2 (100 BYTE)
    )
;
ALTER TABLE CRIANCA
    ADD CONSTRAINT CRIANCA_PK PRIMARY KEY ( num_cartao ) ;

CREATE TABLE DOACAO
    (
     id_doacao   NUMBER  NOT NULL ,
     data_doacao DATE  NOT NULL ,
     id_doador   NUMBER  NOT NULL
    )
;
ALTER TABLE DOACAO
    ADD CONSTRAINT DOACAO_PK PRIMARY KEY ( id_doacao ) ;

CREATE TABLE DOADOR
    (
     id_doador   NUMBER  NOT NULL ,
     nome_doador VARCHAR2 (100 BYTE)  NOT NULL ,
     tipo_doador VARCHAR2 (20)  NOT NULL ,
     contacto VARCHAR2(50) NOT NULL,
     endereco    VARCHAR2 (200 BYTE) ,
     observacoes VARCHAR2 (300 BYTE)
    )
;

ALTER TABLE DOADOR
    ADD
    CHECK (tipo_doador IN ('Individual','Institucional'))
;
ALTER TABLE DOADOR
    ADD CONSTRAINT DOADOR_PK PRIMARY KEY ( id_doador ) ;

ALTER TABLE DOADOR
    ADD CONSTRAINT DOADOR__UN UNIQUE ( nome_doador , contacto ) ;

CREATE TABLE EBOOK
    (
     id_material     NUMBER  NOT NULL ,
     formato         VARCHAR2 (4)  NOT NULL ,
     tamanho_arquivo NUMBER (8,2)  NOT NULL ,
     url_acesso      VARCHAR2 (300 BYTE)  NOT NULL
    )
;

ALTER TABLE EBOOK
    ADD
    CHECK (formato IN ('PDF','EPUB','MOBI','CD','PEN'))
;
ALTER TABLE EBOOK
    ADD CONSTRAINT EBOOK_PK PRIMARY KEY ( id_material ) ;

ALTER TABLE EBOOK
    ADD CONSTRAINT EBOOK__UN UNIQUE ( url_acesso ) ;

CREATE TABLE EMPRESTIMO
    (
     id_emprestimo           NUMBER  NOT NULL ,
     id_material             NUMBER  NOT NULL ,
     multa_valor             NUMBER (8,2) ,
     id_funcionario          NUMBER  NOT NULL ,
     data_retirada           DATE  NOT NULL ,
     prazo_devolucao         DATE  NOT NULL ,
     data_devolucao          DATE ,
     estado_material_saida   VARCHAR2 (20 BYTE)  NOT NULL ,
     estado_material_retorno VARCHAR2 (10 BYTE) ,
     observacoes_devolucao   VARCHAR2 (300 BYTE) ,
     num_cartao              VARCHAR2 (12 BYTE)  NOT NULL ,
     multa_paga              CHAR (1 BYTE)  NOT NULL ,
     data_pagamento_multa    DATE
    )
;

ALTER TABLE EMPRESTIMO
    ADD
    CHECK (multa_valor >= 0)
;

ALTER TABLE EMPRESTIMO
    ADD
    CHECK (estado_material_retorno IN ('Bom','Degradado','Perdido'))
;

ALTER TABLE EMPRESTIMO
    ADD
    CHECK (multa_paga IN ('S', 'N'))
;
ALTER TABLE EMPRESTIMO
    ADD CONSTRAINT EMPRESTIMO_CK_DataDevolucao
    CHECK (data_devolucao IS NULL OR data_devolucao >= data_retirada)
;
ALTER TABLE EMPRESTIMO
    ADD CONSTRAINT EMPRESTIMO_PK PRIMARY KEY ( id_emprestimo ) ;

CREATE TABLE EVENTO
    (
     id_evento        NUMBER  NOT NULL ,
     titulo_evento    VARCHAR2 (100 BYTE)  NOT NULL ,
     descricao_evento VARCHAR2 (500)  NOT NULL ,
     publico_alvo     VARCHAR2 (22 BYTE)  NOT NULL ,
     data_evento      DATE  NOT NULL ,
     recorrente       CHAR (1 BYTE)  NOT NULL ,
     id_biblioteca    NUMBER  NOT NULL
    )
;

ALTER TABLE EVENTO
    ADD
    CHECK (recorrente IN ('S','N'))
;
ALTER TABLE EVENTO
    ADD CONSTRAINT EVENTO_PK PRIMARY KEY ( id_evento ) ;

CREATE TABLE EVENTO_RECURSO
    (
     id_recurso   NUMBER  NOT NULL ,
     nome_recurso VARCHAR2 (100 BYTE)  NOT NULL ,
     quantidade   NUMBER (4)  NOT NULL ,
     id_evento    NUMBER  NOT NULL
    )
;
ALTER TABLE EVENTO_RECURSO
    ADD CONSTRAINT EVENTO_RECURSO_PK PRIMARY KEY ( id_recurso ) ;

CREATE TABLE FUNCAO_FUNCIONARIO
    (
     id_funcao    NUMBER  NOT NULL ,
     nome_funcao  VARCHAR2 (15 BYTE)  NOT NULL ,
     nivel_acesso VARCHAR2 (15 BYTE)  NOT NULL
    )
;
ALTER TABLE FUNCAO_FUNCIONARIO
    ADD CONSTRAINT FUNCAO_FUNCIONARIO_PK PRIMARY KEY ( id_funcao ) ;

ALTER TABLE FUNCAO_FUNCIONARIO
    ADD CONSTRAINT FUNCAO_FUNCIONARIO__UN UNIQUE ( nome_funcao ) ;

CREATE TABLE FUNCIONARIO
    (
     id_funcionario   NUMBER  NOT NULL ,
     nome_funcionario VARCHAR2 (100 BYTE)  NOT NULL ,
     genero           VARCHAR2 (9 BYTE)  NOT NULL ,
     contacto         VARCHAR2 (50 BYTE)  NOT NULL ,
     data_entrada     DATE  NOT NULL ,
     data_saida       DATE ,
     id_biblioteca    NUMBER  NOT NULL ,
     id_funcao        NUMBER  NOT NULL ,
     email            VARCHAR2 (100 BYTE)  NOT NULL ,
     senha            VARCHAR2 (64 BYTE)  NOT NULL
    )
;
ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FUNCIONARIO_CK_DataSaida
    CHECK (data_saida IS NULL OR data_saida >= data_entrada)
;
ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY ( id_funcionario ) ;

ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FUNCIONARIO__UN UNIQUE ( contacto , email ) ;

CREATE TABLE HORARIO_EV_BIB
    (
     id_horario    NUMBER  NOT NULL ,
     dia_semana    VARCHAR2 (13 BYTE)  NOT NULL ,
     hora_abertura VARCHAR2 (5 BYTE)  NOT NULL ,
     hora_fecho    VARCHAR2 (5 BYTE)  NOT NULL ,
     id_evento     NUMBER ,
     id_biblioteca NUMBER
    )
;
ALTER TABLE HORARIO_EV_BIB
    ADD CONSTRAINT HORARIO_EV_BIB_PK PRIMARY KEY ( id_horario ) ;

CREATE TABLE ITEM_DOACAO
    (
     id_itemDoado   NUMBER  NOT NULL ,
     valor_estimado NUMBER (10,2)  NOT NULL ,
     quantidade     NUMBER (4)  NOT NULL ,
     observacoes    VARCHAR2 (300 BYTE) ,
     id_doacao      NUMBER  NOT NULL ,
     id_biblioteca  NUMBER  NOT NULL
    )
;
ALTER TABLE ITEM_DOACAO
    ADD CONSTRAINT ITEM_DOACAO_PK PRIMARY KEY ( id_itemDoado ) ;

CREATE TABLE LEITOR
    (
     num_cartao         VARCHAR2 (12 BYTE)  NOT NULL ,
     nome_completo      VARCHAR2 (100 BYTE)
         CONSTRAINT NNC_LEITOR_nome_completo NOT NULL ,
     data_nasc          DATE
         CONSTRAINT NNC_LEITOR_data_nasc NOT NULL ,
     genero             VARCHAR2 (9 BYTE)
         CONSTRAINT NNC_LEITOR_genero NOT NULL ,
     nivel_escolar      VARCHAR2 (20 BYTE)
         CONSTRAINT NNC_LEITOR_nivel_escolar NOT NULL ,
     localizacao_leitor VARCHAR2 (200 BYTE)
         CONSTRAINT NNC_LEITOR_localizacao_leitor NOT NULL ,
     contacto           VARCHAR2 (50)
         CONSTRAINT NNC_LEITOR_contacto NOT NULL
    )
;

ALTER TABLE LEITOR
    ADD CONSTRAINT CK_LEITOR_genero
    CHECK (genero IN ('Masculino', 'Feminino'))
;
ALTER TABLE LEITOR
    ADD CONSTRAINT LEITOR_PK PRIMARY KEY ( num_cartao ) ;

CREATE TABLE LIVRO_FISICO
    (
     id_material        NUMBER  NOT NULL ,
     localizacao_fisica VARCHAR2 (50 BYTE)  NOT NULL
    )
;
ALTER TABLE LIVRO_FISICO
    ADD CONSTRAINT LIVRO_FISICO_PK PRIMARY KEY ( id_material ) ;

CREATE TABLE MATERIAL_BIBLIOGRAFICO
    (
     id_material                 NUMBER  NOT NULL ,
     titulo                      VARCHAR2 (200 BYTE)  NOT NULL ,
     autor                       VARCHAR2 (100 BYTE)  NOT NULL ,
     editora                     VARCHAR2 (80 BYTE)  NOT NULL ,
     ano_publicacao              NUMBER (4)  NOT NULL ,
     ISBN                        VARCHAR2 (17 BYTE) ,
     idioma                      VARCHAR2 (30 BYTE)  NOT NULL ,
     num_paginas                 NUMBER (5)  NOT NULL ,
     estado_material_conservacao VARCHAR2 (13 BYTE)  NOT NULL ,
     id_categoria                NUMBER  NOT NULL ,
     id_itemDoado                NUMBER NOT NULL,
     id_biblioteca               NUMBER  NOT NULL
    )
;
ALTER TABLE MATERIAL_BIBLIOGRAFICO
    ADD CONSTRAINT MATERIAL_BIBLIOGRAFICO_PK PRIMARY KEY ( id_material ) ;

ALTER TABLE MATERIAL_BIBLIOGRAFICO
    ADD CONSTRAINT MATERIAL_BIBLIOGRAFICO__UN UNIQUE ( ISBN ) ;

CREATE TABLE PARTICIPACAO_EVENTO
    (
     num_cartao           VARCHAR2 (12 BYTE)  NOT NULL ,
     id_evento            NUMBER  NOT NULL ,
     data_inscricao       DATE  NOT NULL ,
     presenca_confirmacao CHAR (1 BYTE)  NOT NULL
    )
;

ALTER TABLE PARTICIPACAO_EVENTO
    ADD
    CHECK (presenca_confirmacao IN ('S','N'))
;
ALTER TABLE PARTICIPACAO_EVENTO
    ADD CONSTRAINT PARTICIPACAO_EVENTO_PK PRIMARY KEY ( id_evento, num_cartao ) ;

CREATE TABLE PERIODICO
    (
     id_material     NUMBER  NOT NULL ,
     edicao          VARCHAR2 (50 BYTE)  NOT NULL ,
     periodicidade   VARCHAR2 (10 BYTE)  NOT NULL ,
     data_publicacao DATE  NOT NULL ,
     ISSN            VARCHAR2 (9 BYTE)
    )
;

ALTER TABLE PERIODICO
    ADD
    CHECK (periodicidade IN ('Mensal','Trimestral','Anual'))
;
ALTER TABLE PERIODICO
    ADD CONSTRAINT PERIODICO_PK PRIMARY KEY ( id_material ) ;

ALTER TABLE PERIODICO
    ADD CONSTRAINT PERIODICO__UN UNIQUE ( ISSN ) ;

CREATE TABLE PROFESSOR
    (
     num_cartao       VARCHAR2 (12 BYTE)  NOT NULL ,
     escola_instituto VARCHAR2 (100 BYTE)  NOT NULL ,
     disciplina       VARCHAR2 (50 BYTE)  NOT NULL ,
     tipo_ensino      VARCHAR2 (15 BYTE)  NOT NULL
    )
;
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY ( num_cartao ) ;

CREATE TABLE TRANSFERENCIA
    (
     id_transferencia           NUMBER  NOT NULL ,
     data_solicitacao           DATE  NOT NULL ,
     data_aprovacao_destino     DATE ,
     data_conclusao             DATE ,
     motivo                     VARCHAR2 (300 BYTE)  NOT NULL ,
     estado_transferencia       VARCHAR2 (20 BYTE)  NOT NULL ,
     id_biblioteca_origem       NUMBER  NOT NULL ,
     id_biblioteca_destino      NUMBER  NOT NULL ,
     id_material                NUMBER  NOT NULL ,
     id_funcionario_solicitante NUMBER  NOT NULL ,
     id_funcionario_aprovador   NUMBER
    )
;

ALTER TABLE TRANSFERENCIA
    ADD
    CHECK (estado_transferencia IN ('Pendente','Aprovada','Rejeitada','Concluida'))
;
ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_PK PRIMARY KEY ( id_transferencia ) ;

ALTER TABLE ADULTO
    ADD CONSTRAINT ADULTO_LEITOR_FK FOREIGN KEY
    (
     num_cartao
    )
    REFERENCES LEITOR
    (
     num_cartao
    )
;

ALTER TABLE CERTIFICADO_DOACAO
    ADD CONSTRAINT CERTIFICADO_DOACAO_DOACAO_FK FOREIGN KEY
    (
     id_doacao
    )
    REFERENCES DOACAO
    (
     id_doacao
    )
    ON DELETE CASCADE
;

ALTER TABLE CRIANCA
    ADD CONSTRAINT CRIANCA_LEITOR_FK FOREIGN KEY
    (
     num_cartao
    )
    REFERENCES LEITOR
    (
     num_cartao
    )
;

ALTER TABLE DOACAO
    ADD CONSTRAINT DOACAO_DOADOR_FK FOREIGN KEY
    (
     id_doador
    )
    REFERENCES DOADOR
    (
     id_doador
    )
;

ALTER TABLE EBOOK
    ADD CONSTRAINT EBOOK_MATERIAL_FK FOREIGN KEY
    (
     id_material
    )
    REFERENCES MATERIAL_BIBLIOGRAFICO
    (
     id_material
    )
    ON DELETE CASCADE
;

ALTER TABLE EMPRESTIMO
    ADD CONSTRAINT EMPRESTIMO_FUNCIONARIO_FK FOREIGN KEY
    (
     id_funcionario
    )
    REFERENCES FUNCIONARIO
    (
     id_funcionario
    )
;

ALTER TABLE EMPRESTIMO
    ADD CONSTRAINT EMPRESTIMO_LEITOR_FK FOREIGN KEY
    (
     num_cartao
    )
    REFERENCES LEITOR
    (
     num_cartao
    )
;

ALTER TABLE EVENTO
    ADD CONSTRAINT EVENTO_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE EVENTO_RECURSO
    ADD CONSTRAINT EVENTO_RECURSO_EVENTO_FK FOREIGN KEY
    (
     id_evento
    )
    REFERENCES EVENTO
    (
     id_evento
    )
    ON DELETE CASCADE
;

ALTER TABLE LIVRO_FISICO
    ADD CONSTRAINT FISICO_MATERIAL_FK FOREIGN KEY
    (
     id_material
    )
    REFERENCES MATERIAL_BIBLIOGRAFICO
    (
     id_material
    )
    ON DELETE CASCADE
;

ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FUNCAO_FUNCIONARIO_FK FOREIGN KEY
    (
     id_funcao
    )
    REFERENCES FUNCAO_FUNCIONARIO
    (
     id_funcao
    )
;

ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT FUNCIONARIO_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE BIBLIOTECA
    ADD CONSTRAINT FUNCIONARIO_FK FOREIGN KEY
    (
     id_responsavel
    )
    REFERENCES FUNCIONARIO
    (
     id_funcionario
    )
;

ALTER TABLE HORARIO_EV_BIB
    ADD CONSTRAINT HORARIO_EV_BIB_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
    ON DELETE CASCADE
;

ALTER TABLE HORARIO_EV_BIB
    ADD CONSTRAINT HORARIO_EV_BIB_EVENTO_FK FOREIGN KEY
    (
     id_evento
    )
    REFERENCES EVENTO
    (
     id_evento
    )
    ON DELETE CASCADE
;

ALTER TABLE ITEM_DOACAO
    ADD CONSTRAINT ITEM_DOACAO_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE ITEM_DOACAO
    ADD CONSTRAINT ITEM_DOACAO_DOACAO_FK FOREIGN KEY
    (
     id_doacao
    )
    REFERENCES DOACAO
    (
     id_doacao
    )
    ON DELETE CASCADE
;

ALTER TABLE EMPRESTIMO
    ADD CONSTRAINT MATERIAL_BIBLIOGRAFICO_FK FOREIGN KEY
    (
     id_material
    )
    REFERENCES MATERIAL_BIBLIOGRAFICO
    (
     id_material
    )
;

ALTER TABLE MATERIAL_BIBLIOGRAFICO
    ADD CONSTRAINT MATERIAL_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE MATERIAL_BIBLIOGRAFICO
    ADD CONSTRAINT MATERIAL_CATEGORIA_FK FOREIGN KEY
    (
     id_categoria
    )
    REFERENCES CATEGORIA
    (
     id_categoria
    )
;

ALTER TABLE MATERIAL_BIBLIOGRAFICO
    ADD CONSTRAINT MATERIAL_ITEM_DOACAO_FK FOREIGN KEY
    (
     id_itemDoado
    )
    REFERENCES ITEM_DOACAO
    (
     id_itemDoado
    )
;

ALTER TABLE PARTICIPACAO_EVENTO
    ADD CONSTRAINT PARTICIPACAO_EVENTO_EVENTO_FK FOREIGN KEY
    (
     id_evento
    )
    REFERENCES EVENTO
    (
     id_evento
    )
    ON DELETE CASCADE
;

ALTER TABLE PARTICIPACAO_EVENTO
    ADD CONSTRAINT PARTICIPACAO_EVENTO_LEITOR_FK FOREIGN KEY
    (
     num_cartao
    )
    REFERENCES LEITOR
    (
     num_cartao
    )
    ON DELETE CASCADE
;

ALTER TABLE PERIODICO
    ADD CONSTRAINT PERIODICO_MATERIAL_FK FOREIGN KEY
    (
     id_material
    )
    REFERENCES MATERIAL_BIBLIOGRAFICO
    (
     id_material
    )
    ON DELETE CASCADE
;

ALTER TABLE PROFESSOR
    ADD CONSTRAINT PROFESSOR_ADULTO_FK FOREIGN KEY
    (
     num_cartao
    )
    REFERENCES ADULTO
    (
     num_cartao
    )
;

ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_BIBLIOTECA_FK FOREIGN KEY
    (
     id_biblioteca_origem
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_BIBLIOTECA_FKv1 FOREIGN KEY
    (
     id_biblioteca_destino
    )
    REFERENCES BIBLIOTECA
    (
     id_biblioteca
    )
;

ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_FUNCIONARIO_FK FOREIGN KEY
    (
     id_funcionario_solicitante
    )
    REFERENCES FUNCIONARIO
    (
     id_funcionario
    )
;

ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_FUNCIONARIO_FKv1 FOREIGN KEY
    (
     id_funcionario_aprovador
    )
    REFERENCES FUNCIONARIO
    (
     id_funcionario
    )
;

ALTER TABLE TRANSFERENCIA
    ADD CONSTRAINT TRANSFERENCIA_MATERIAL_FK FOREIGN KEY
    (
     id_material
    )
    REFERENCES MATERIAL_BIBLIOGRAFICO
    (
     id_material
    )
;