-- ==========================================
-- DROPS DAS SEQUÊNCIAS
-- ==========================================
DROP SEQUENCE SEQ_FUNCAO;
DROP SEQUENCE SEQ_FUNCIONARIO;
DROP SEQUENCE SEQ_HORARIO_FUNC;
DROP SEQUENCE SEQ_DOADOR;
DROP SEQUENCE SEQ_DOACAO;
DROP SEQUENCE SEQ_ITEMDOADO;
DROP SEQUENCE SEQ_CERTIFICADO;
DROP SEQUENCE SEQ_AUDITORIA;

-- ==========================================
-- CRIAÇÃO DAS SEQUÊNCIAS
-- ==========================================
CREATE SEQUENCE SEQ_FUNCAO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCIONARIO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HORARIO_FUNC    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOADOR          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOACAO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEMDOADO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CERTIFICADO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDITORIA       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

