-- DOACAO
CREATE INDEX id_doa ON DOACAO(id_doador)   TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX id_dt  ON DOACAO(data_doacao) TABLESPACE tbs_NACIONALDB_idx;

-- CERTIFICADO_DOACAO
CREATE INDEX icert_doa ON CERTIFICADO_DOACAO(id_doacao)       TABLESPACE tbs_NACIONALDB_idx;

-- FUNCIONARIO
CREATE INDEX if_bib  ON FUNCIONARIO(cod_biblioteca) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX if_func ON FUNCIONARIO(id_funcao)      TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX if_form ON FUNCIONARIO(formacao)       TABLESPACE tbs_NACIONALDB_idx;

-- FUNCIONARIO_HABILIDADE
CREATE INDEX ifh_func ON FUNCIONARIO_HABILIDADE(cod_funcionario) TABLESPACE tbs_NACIONALDB_idx;

-- HORARIO_FUNCIONARIO
CREATE INDEX ihf_func ON HORARIO_FUNCIONARIO(cod_funcionario) TABLESPACE tbs_NACIONALDB_idx;

-- LEITOR (movido para este nó na v3)
CREATE INDEX il_bib    ON LEITOR(cod_biblioteca)        TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX il_status ON LEITOR(status_leitor)         TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX il_nome   ON LEITOR(nome_completo)         TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX il_pont   ON LEITOR(historico_pontualidade) TABLESPACE tbs_NACIONALDB_idx;

-- ADULTO
CREATE INDEX ia_lit ON ADULTO(nivel_literacia) TABLESPACE tbs_NACIONALDB_idx;

-- AUDITORIA_OPERACOES
CREATE INDEX iaud_func ON AUDITORIA_OPERACOES(cod_funcionario) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX iaud_data ON AUDITORIA_OPERACOES(data_operacao)   TABLESPACE tbs_NACIONALDB_idx;