-- Utilizador principal
DROP USER usr_NACIONALDB CASCADE;
CREATE USER usr_NACIONALDB IDENTIFIED BY HTAJnr#020403
  DEFAULT TABLESPACE tbs_NACIONALDB
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON tbs_NACIONALDB
  QUOTA UNLIMITED ON tbs_NACIONALDB_idx;

-- Utilizador de aplicação
DROP USER app_NACIONALDB CASCADE;
CREATE USER app_NACIONALDB IDENTIFIED BY HTAJnr#22041
  DEFAULT TABLESPACE tbs_NACIONALDB
  TEMPORARY TABLESPACE TEMP;

  