-- DOACAO
CREATE INDEX id_doa ON DOACAO(id_doador) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX id_dt  ON DOACAO(data_doacao) TABLESPACE tbs_NACIONALDB_idx;

-- FUNCIONARIO
CREATE INDEX if_bib  ON FUNCIONARIO(cod_biblioteca) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX if_func ON FUNCIONARIO(id_funcao) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX if_form ON FUNCIONARIO(formacao) TABLESPACE tbs_NACIONALDB_idx;

-- PROGRAMA_ALFABETIZACAO
CREATE INDEX iprog_bib ON PROGRAMA_ALFABETIZACAO(cod_biblioteca) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX iprog_est ON PROGRAMA_ALFABETIZACAO(estado_programa) TABLESPACE tbs_NACIONALDB_idx;

-- PARTICIPACAO_PROGRAMA
CREATE INDEX ipp_prog  ON PARTICIPACAO_PROGRAMA(cod_programa) TABLESPACE tbs_NACIONALDB_idx;
CREATE INDEX ipp_nivel ON PARTICIPACAO_PROGRAMA(id_nivel_atual) TABLESPACE tbs_NACIONALDB_idx;

-- FUNCIONARIO_HABILIDADE
CREATE INDEX ifh_func ON FUNCIONARIO_HABILIDADE(cod_funcionario) TABLESPACE tbs_NACIONALDB_idx;

-- HORARIO_FUNCIONARIO
CREATE INDEX ihf_func ON HORARIO_FUNCIONARIO(cod_funcionario) TABLESPACE tbs_NACIONALDB_idx;