-- ==========================================
-- DROPS DAS SEQUÊNCIAS
-- ==========================================
DROP SEQUENCE SEQ_HORARIO_BIB;
DROP SEQUENCE SEQ_CATEGORIA;
DROP SEQUENCE SEQ_CERTIFICADO;
DROP SEQUENCE SEQ_DOACAO;
DROP SEQUENCE SEQ_DOADOR;
DROP SEQUENCE SEQ_EMPRESTIMO;
DROP SEQUENCE SEQ_EVENTO;
DROP SEQUENCE SEQ_RECURSO;
DROP SEQUENCE SEQ_FUNCAO;
DROP SEQUENCE SEQ_HORARIO_FUNC;
DROP SEQUENCE SEQ_HORARIO_EV;
DROP SEQUENCE SEQ_ITEMDOADO;
DROP SEQUENCE SEQ_MATERIAL;
DROP SEQUENCE SEQ_SUSPENSAO;
DROP SEQUENCE SEQ_TRANSFERENCIA;
DROP SEQUENCE SEQ_AVALIACAO;
DROP SEQUENCE SEQ_PROGRAMA;
DROP SEQUENCE SEQ_NIVEL;
DROP SEQUENCE SEQ_FUNCIONARIO;

-- ==========================================
-- CRIAÇÃO DAS SEQUÊNCIAS
-- ==========================================
CREATE SEQUENCE SEQ_HORARIO_BIB     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCIONARIO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIA       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CERTIFICADO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOACAO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOADOR          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPRESTIMO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECURSO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCAO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HORARIO_FUNC    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HORARIO_EV      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEMDOADO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MATERIAL        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUSPENSAO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSFERENCIA   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AVALIACAO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROGRAMA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NIVEL           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;