-- Apagar sequencias antigas (se existirem)
DROP SEQUENCE SEQ_BIBLIOTECA;
DROP SEQUENCE SEQ_CATEGORIA;
DROP SEQUENCE SEQ_CERTIFICADO;
DROP SEQUENCE SEQ_DOACAO;
DROP SEQUENCE SEQ_DOADOR;
DROP SEQUENCE SEQ_EMPRESTIMO;
DROP SEQUENCE SEQ_EVENTO;
DROP SEQUENCE SEQ_RECURSO;
DROP SEQUENCE SEQ_FUNCAO;
DROP SEQUENCE SEQ_FUNCIONARIO;
DROP SEQUENCE SEQ_HORARIO;
DROP SEQUENCE SEQ_ITEMDOADO;
DROP SEQUENCE SEQ_MATERIAL;
DROP SEQUENCE SEQ_TRANSFERENCIA;
DROP SEQUENCE SEQ_NUM_CARTAO;

-- Criar sequencias com o valor inicial correto apos a populacao massiva
CREATE SEQUENCE SEQ_BIBLIOTECA START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CERTIFICADO START WITH 4 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOACAO START WITH 8 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOADOR START WITH 7 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPRESTIMO START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTO START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECURSO START WITH 23 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCAO START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCIONARIO START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HORARIO START WITH 29 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEMDOADO START WITH 8 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MATERIAL START WITH 159 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSFERENCIA START WITH 4 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NUM_CARTAO START WITH 14 INCREMENT BY 1 NOCACHE NOCYCLE;