-- Limpar roles de versoes anteriores (tolerante a ORA-01919)
BEGIN EXECUTE IMMEDIATE 'DROP ROLE role_NACIONALDB_read';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE role_NACIONALDB_write'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE role_nac_visitante';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE role_nac_leitor_tipo';  EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Roles locais do no (sessao directa — nao transitam por dblink)
CREATE ROLE role_NACIONALDB_read;
CREATE ROLE role_NACIONALDB_write;

-- Atribuir ao utilizador de aplicacao local
GRANT role_NACIONALDB_read  TO app_NACIONALDB;
GRANT role_NACIONALDB_write TO app_NACIONALDB;

-- Privilégios de sessão

REVOKE CREATE SESSION FROM usr_NACIONALDB;
REVOKE CREATE SESSION FROM app_NACIONALDB;
REVOKE CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
CREATE TRIGGER, CREATE PROCEDURE, CREATE SYNONYM, CREATE PUBLIC SYNONYM,
CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE PUBLIC DATABASE LINK
FROM usr_NACIONALDB;

GRANT CREATE SESSION TO usr_NACIONALDB;
GRANT CREATE SESSION TO app_NACIONALDB;

-- Privilégios DDL ao utilizador principal
-- CREATE PUBLIC DATABASE LINK é necessário para que app_NACIONALDB (user da app)
-- possa resolver os links usados pelos PUBLIC synonyms.
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE TRIGGER, CREATE PROCEDURE, CREATE SYNONYM,
      CREATE PUBLIC SYNONYM, CREATE MATERIALIZED VIEW,
      CREATE DATABASE LINK, CREATE PUBLIC DATABASE LINK,
      DROP PUBLIC DATABASE LINK TO usr_NACIONALDB;

