-- Tablespace de dados

DROP TABLESPACE tbs_NACIONALDB
  INCLUDING CONTENTS AND DATAFILES
  CASCADE CONSTRAINTS;

CREATE TABLESPACE tbs_NACIONALDB
  DATAFILE '/usr/lib/oracle/xe/oradata/XE/tbs_NACIONALDB.dbf'
  SIZE 100M
  AUTOEXTEND ON NEXT 10M MAXSIZE 500M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;

-- Tablespace de índices (separada dos dados — boa prática)

DROP TABLESPACE tbs_NACIONALDB_idx
  INCLUDING CONTENTS AND DATAFILES
  CASCADE CONSTRAINTS;

CREATE TABLESPACE tbs_NACIONALDB_idx
  DATAFILE '/usr/lib/oracle/xe/oradata/XE/tbs_NACIONALDB_idx.dbf'
  SIZE 50M
  AUTOEXTEND ON NEXT 5M MAXSIZE 200M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;