-- Roles
DROP ROLE role_NACIONALDB_read;
CREATE ROLE role_NACIONALDB_read;

DROP ROLE role_NACIONALDB_write;
CREATE ROLE role_NACIONALDB_write;

-- Privilégios de sessão

REVOKE role_NACIONALDB_read FROM app_NACIONALDB;
REVOKE CREATE SESSION FROM usr_NACIONALDB;
REVOKE CREATE SESSION FROM app_NACIONALDB;
REVOKE CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
CREATE TRIGGER, CREATE PROCEDURE, CREATE SYNONYM, CREATE PUBLIC SYNONYM,
CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE PUBLIC DATABASE LINK
FROM usr_NACIONALDB;

GRANT CREATE SESSION TO usr_NACIONALDB;
GRANT CREATE SESSION TO app_NACIONALDB;

-- Privilégios DDL ao utilizador principal
-- CREATE PUBLIC DATABASE LINK é necessário para que app_NACIONALDB (user da app)
-- possa resolver os links usados pelos PUBLIC synonyms.
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE TRIGGER, CREATE PROCEDURE, CREATE SYNONYM,
      CREATE PUBLIC SYNONYM, CREATE MATERIALIZED VIEW,
      CREATE DATABASE LINK, CREATE PUBLIC DATABASE LINK,
      DROP PUBLIC DATABASE LINK TO usr_NACIONALDB;

-- Roles ao utilizador de aplicação
-- SYSDBA é obrigatório aqui — usr_NACIONALDB não tem ADMIN OPTION nestes roles.
GRANT role_NACIONALDB_read  TO app_NACIONALDB;
GRANT role_NACIONALDB_write TO app_NACIONALDB;